/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Recog;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import edu.cmu.sphinx.frontend.util.Microphone;
import edu.cmu.sphinx.recognizer.Recognizer;
import edu.cmu.sphinx.result.Result;
import edu.cmu.sphinx.util.props.ConfigurationManager;
import edu.cmu.sphinx.util.props.PropertyException;

/**
 *
 * @author User
 */
public class Main extends javax.swing.JFrame {

    
    
    public Main() {
        initComponents();
//        url = Main.class.getResource("recallassist.config.xml");
        
    }
//    URL url;
//    ConfigurationManager cm;
//    Recognizer recognizer;
//    Microphone microphone;
//    Result result;
//    String resultText;
    String Content="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
//    int button=0;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblcontent = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(765, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setText("ByDay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(670, 10, 63, 23);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(765, 474));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time", "Content"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(510, 60, 220, 380);

        jButton3.setText("Start Recording");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(200, 210, 120, 40);

        jLabel1.setText("You Said - ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 280, 60, 14);

        lblcontent.setText("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz");
        getContentPane().add(lblcontent);
        lblcontent.setBounds(90, 280, 400, 14);

        jButton4.setText("View Events");
        getContentPane().add(jButton4);
        jButton4.setBounds(20, 340, 120, 40);

        jButton5.setText("Predict Events");
        getContentPane().add(jButton5);
        jButton5.setBounds(20, 400, 120, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//   private void recordingstart(URL url)
//    {
//        try {
//            if (button==0)
//            {
//            this.cm = new ConfigurationManager(url);
//
//	    recognizer = (Recognizer) cm.lookup("recognizer");
//	    microphone = (Microphone) cm.lookup("microphone");
//            }
//            
//            
//            button=1;
//            /* allocate the resource necessary for the recognizer */
//            recognizer.allocate();
//
//            
//            /* the microphone will keep recording until the program exits */
//	    if (microphone.startRecording()) {
//
//		System.out.println
//		    ("Say: (Good morning | Hello) " +
//                     "( Bhiksha | Evandro | Paul | Philip | Rita | Will )");
//
//		
//		    System.out.println
//			("Start speaking. Press Ctrl-C to quit.\n");
//
//                    /*
//                     * This method will return when the end of speech
//                     * is reached. Note that the endpointer will determine
//                     * the end of speech.
//                     */ 
//		     result = recognizer.recognize();
//		    
//		    if (result != null) {
//			resultText = result.getBestFinalResultNoFiller();
//			System.out.println("You said: " + resultText + "\n");
//		    } else {
//			System.out.println("I can't hear what you said.\n");
//		    }
//		
//	    } else {
//		System.out.println("Cannot start microphone.");
//		recognizer.deallocate();
//		System.exit(1);
//	    }
//        } catch (IOException e) {
//            System.err.println("Problem when loading HelloWorld: " + e);
//            e.printStackTrace();
//        } catch (PropertyException e) {
//            System.err.println("Problem configuring HelloWorld: " + e);
//            e.printStackTrace();
//        } catch (InstantiationException e) {
//            System.err.println("Problem creating HelloWorld: " + e);
//            e.printStackTrace();
//        }
//    }
   
   public void setContent (String Content)
   {
       this.Content=Content;
   }
   
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ByDayy byday;
            byday = new ByDayy("2017-09-03-1");
            
            float Percentage=byday.getPercentageByDay();
           
            
            String [] occurdates = byday.getOccureDates();
            JOptionPane.showMessageDialog(null, Percentage+"%");
            
            for (int i =0 ;i<occurdates.length;i++)
            {
                JOptionPane.showMessageDialog(null, occurdates[i]);
            }
        } catch (ParseException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Record obj = new Record();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (Content.length()>0)
        {
            lblcontent.setText(Content);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblcontent;
    // End of variables declaration//GEN-END:variables
}
